branch-defaults:
  master:
    environment: uclive-dev
    group_suffix: null
global:
  application_name: uclive
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: us-west-1
  profile: eb-cli
  sc: git
